### ISSUE TITLE
Make the App Responsive

### ISSUE THREAD

**Issue by MarcoMorawec** [tzinser/splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by tzinser** [comment]
Thanks.  Added the viewport meta tag and pushed the changes.

**Comment by MarcoMorawec** [comment]
@tzinser :+1: and great job. 

Looks like [this commit](https://github.com/tzinser/splurty/commit/197b779e07a2c6b6356b8bd62b9bc9d4115670b5) fixes it nicely.

Make sure you close the issue, now that you're done with it.

**Comment by tzinser** [comment]
Closing issue, added viewport meta tag for mobile devices to properly render and enable touch zooming.
